/**
 * Change Provenance Tracking
 *
 * Every line of prose is tagged with its origin:
 *   author          — written by the author
 *   ai-drafted      — generated by AI in draft phase
 *   ai-revised      — revised by AI (approved as-is)
 *   ai-edited       — edited by AI (approved as-is)
 *   ai-modified     — AI-suggested, modified by author before acceptance
 *   author-revised  — author revised AI output
 *
 * Provenance stored as a sidecar JSON per chapter: ./book/content/chapter-NN.provenance.json
 */

import fs from 'fs-extra';
import path from 'path';

// ─── Types ───────────────────────────────────────────────────────────────

/** Origin classification for a line of prose. */
export type ProvenanceType =
  | 'author'
  | 'ai-drafted'
  | 'ai-revised'
  | 'ai-edited'
  | 'ai-modified'
  | 'author-revised';

/** Provenance metadata for a single line of prose. */
export interface LineProvenance {
  lineNumber: number;
  content: string;           // the line content (for verification)
  origin: ProvenanceType;
  phase?: string;            // which phase created/modified this line
  timestamp: string;
  approvedBy?: 'author' | 'ai';  // who approved the final form
}

/** Per-chapter provenance data with line-level tracking and statistics. */
export interface ChapterProvenance {
  chapterNumber: number;
  lines: LineProvenance[];
  statistics: ProvenanceStatistics;
  updatedAt: string;
}

/** Counts and percentages by origin type for a chapter. */
export interface ProvenanceStatistics {
  totalLines: number;
  byOrigin: Record<ProvenanceType, number>;
  byOriginPercent: Record<ProvenanceType, number>;
  authorPercent: number;       // author + author-revised
  aiPercent: number;           // ai-drafted + ai-revised + ai-edited + ai-modified
  aiModifiedPercent: number;   // ai-modified (AI suggested, author changed)
}

// ─── Initialization ──────────────────────────────────────────────────────────

/**
 * Initialize provenance for a newly drafted chapter.
 * All lines are tagged as 'ai-drafted' (or 'author' if from author's draft material).
 */
export function initializeProvenance(
  chapterNumber: number,
  content: string,
  source: 'ai-draft' | 'author-draft' = 'ai-draft'
): ChapterProvenance {
  const lines = content.split('\n');
  const timestamp = new Date().toISOString();
  const origin: ProvenanceType = source === 'ai-draft' ? 'ai-drafted' : 'author';

  const lineProvenances: LineProvenance[] = lines.map((line, i) => ({
    lineNumber: i + 1,
    content: line,
    origin,
    phase: source === 'ai-draft' ? 'draft' : 'author-draft',
    timestamp,
  }));

  return {
    chapterNumber,
    lines: lineProvenances,
    statistics: computeStatistics(lineProvenances),
    updatedAt: timestamp,
  };
}

// ─── Update on Revision/Edit ──────────────────────────────────────────────────

/**
 * Update provenance after a revision or edit pass.
 * Compares the new content against the existing provenance and tags changed lines.
 */
export function updateProvenance(
  existing: ChapterProvenance,
  newContent: string,
  phase: 'revise' | 'edit',
  approvedHunks?: Set<number>  // line numbers that were approved by the author
): ChapterProvenance {
  const newLines = newContent.split('\n');
  const oldLineMap = new Map(existing.lines.map(l => [l.lineNumber, l]));
  const timestamp = new Date().toISOString();

  const updatedLines: LineProvenance[] = newLines.map((line, i) => {
    const lineNum = i + 1;
    const oldLine = oldLineMap.get(lineNum);

    // Line unchanged — keep old provenance
    if (oldLine && oldLine.content === line) {
      return oldLine;
    }

    // New or changed line
    const wasApproved = approvedHunks?.has(lineNum) ?? true;
    const origin: ProvenanceType = wasApproved
      ? (phase === 'revise' ? 'ai-revised' : 'ai-edited')
      : 'ai-modified';

    return {
      lineNumber: lineNum,
      content: line,
      origin,
      phase,
      timestamp,
      approvedBy: wasApproved ? 'author' : 'author',
    };
  });

  return {
    chapterNumber: existing.chapterNumber,
    lines: updatedLines,
    statistics: computeStatistics(updatedLines),
    updatedAt: timestamp,
  };
}

/**
 * Mark lines as author-revised when the author manually edits outside an AI pass.
 */
export function markAuthorRevision(
  existing: ChapterProvenance,
  newContent: string
): ChapterProvenance {
  const newLines = newContent.split('\n');
  const oldLineMap = new Map(existing.lines.map(l => [l.lineNumber, l]));
  const timestamp = new Date().toISOString();

  const updatedLines: LineProvenance[] = newLines.map((line, i) => {
    const lineNum = i + 1;
    const oldLine = oldLineMap.get(lineNum);

    if (oldLine && oldLine.content === line) {
      return oldLine;
    }

    return {
      lineNumber: lineNum,
      content: line,
      origin: 'author-revised',
      phase: 'author-manual-edit',
      timestamp,
      approvedBy: 'author',
    };
  });

  return {
    chapterNumber: existing.chapterNumber,
    lines: updatedLines,
    statistics: computeStatistics(updatedLines),
    updatedAt: timestamp,
  };
}

// ─── Statistics ────────────────────────────────────────────────────────────────

function computeStatistics(lines: LineProvenance[]): ProvenanceStatistics {
  const byOrigin = {
    'author': 0,
    'ai-drafted': 0,
    'ai-revised': 0,
    'ai-edited': 0,
    'ai-modified': 0,
    'author-revised': 0,
  };

  for (const line of lines) {
    byOrigin[line.origin]++;
  }

  const totalLines = lines.length;
  const byOriginPercent = {} as Record<ProvenanceType, number>;
  for (const key of Object.keys(byOrigin) as ProvenanceType[]) {
    byOriginPercent[key] = totalLines > 0 ? (byOrigin[key] / totalLines) * 100 : 0;
  }

  const authorPercent = byOrigin['author'] + byOrigin['author-revised'];
  const aiPercent = byOrigin['ai-drafted'] + byOrigin['ai-revised'] + byOrigin['ai-edited'] + byOrigin['ai-modified'];
  const aiModifiedPercent = byOrigin['ai-modified'];

  return {
    totalLines,
    byOrigin,
    byOriginPercent,
    authorPercent: totalLines > 0 ? (authorPercent / totalLines) * 100 : 0,
    aiPercent: totalLines > 0 ? (aiPercent / totalLines) * 100 : 0,
    aiModifiedPercent: totalLines > 0 ? (aiModifiedPercent / totalLines) * 100 : 0,
  };
}

// ─── Manuscript-Level Statistics ──────────────────────────────────────────────

/** Aggregate provenance statistics across all chapters of a manuscript. */
export interface ManuscriptProvenance {
  totalChapters: number;
  totalLines: number;
  aggregateByOrigin: Record<ProvenanceType, number>;
  aggregateByOriginPercent: Record<ProvenanceType, number>;
  authorPercent: number;
  aiPercent: number;
  aiModifiedPercent: number;
  perChapter: { chapter: number; authorPercent: number; aiPercent: number }[];
}

/** Aggregate per-chapter provenance data into manuscript-level statistics. */
export function aggregateProvenance(chapters: ChapterProvenance[]): ManuscriptProvenance {
  const aggregate = {
    'author': 0,
    'ai-drafted': 0,
    'ai-revised': 0,
    'ai-edited': 0,
    'ai-modified': 0,
    'author-revised': 0,
  };

  let totalLines = 0;
  const perChapter: { chapter: number; authorPercent: number; aiPercent: number }[] = [];

  for (const ch of chapters) {
    for (const line of ch.lines) {
      aggregate[line.origin]++;
      totalLines++;
    }
    perChapter.push({
      chapter: ch.chapterNumber,
      authorPercent: ch.statistics.authorPercent,
      aiPercent: ch.statistics.aiPercent,
    });
  }

  const aggregatePercent = {} as Record<ProvenanceType, number>;
  for (const key of Object.keys(aggregate) as ProvenanceType[]) {
    aggregatePercent[key] = totalLines > 0 ? (aggregate[key] / totalLines) * 100 : 0;
  }

  const authorCount = aggregate['author'] + aggregate['author-revised'];
  const aiCount = aggregate['ai-drafted'] + aggregate['ai-revised'] + aggregate['ai-edited'] + aggregate['ai-modified'];

  return {
    totalChapters: chapters.length,
    totalLines,
    aggregateByOrigin: aggregate,
    aggregateByOriginPercent: aggregatePercent,
    authorPercent: totalLines > 0 ? (authorCount / totalLines) * 100 : 0,
    aiPercent: totalLines > 0 ? (aiCount / totalLines) * 100 : 0,
    aiModifiedPercent: aggregatePercent['ai-modified'],
    perChapter,
  };
}

// ─── Persistence ────────────────────────────────────────────────────────────

/** Write chapter provenance to a sidecar JSON file. */
export function saveProvenance(projectRoot: string, provenance: ChapterProvenance): void {
  const dir = path.join(projectRoot, 'book', 'content');
  const filename = `chapter-${String(provenance.chapterNumber).padStart(5, '0')}.provenance.json`;
  fs.writeJsonSync(path.join(dir, filename), provenance, { spaces: 2 });
}

/** Read chapter provenance from a sidecar JSON file, or null if not found. */
export function loadProvenance(projectRoot: string, chapterNumber: number): ChapterProvenance | null {
  const dir = path.join(projectRoot, 'book', 'content');
  const filename = `chapter-${String(chapterNumber).padStart(5, '0')}.provenance.json`;
  const filepath = path.join(dir, filename);
  if (!fs.existsSync(filepath)) return null;
  return fs.readJsonSync(filepath);
}

// ─── Formatting ────────────────────────────────────────────────────────────

/** Format a chapter's provenance statistics as a markdown display. */
export function formatProvenanceForDisplay(provenance: ChapterProvenance): string {
  const stats = provenance.statistics;
  return [
    `## Provenance: Chapter ${provenance.chapterNumber}`,
    '',
    `**Total lines**: ${stats.totalLines}`,
    `**Author**: ${stats.authorPercent.toFixed(1)}% (${stats.byOrigin['author']} original + ${stats.byOrigin['author-revised']} revised)`,
    `**AI-generated**: ${stats.aiPercent.toFixed(1)}% (${stats.byOrigin['ai-drafted']} drafted + ${stats.byOrigin['ai-revised']} revised + ${stats.byOrigin['ai-edited']} edited + ${stats.byOrigin['ai-modified']} modified)`,
    `**AI-modified by author**: ${stats.aiModifiedPercent.toFixed(1)}%`,
    '',
    '### Breakdown by Origin',
    ...Object.entries(stats.byOrigin).map(([origin, count]) =>
      `- ${origin}: ${count} (${stats.byOriginPercent[origin as ProvenanceType].toFixed(1)}%)`
    ),
  ].join('\n');
}

/** Format manuscript-level provenance as a markdown report. */
export function formatManuscriptProvenance(mp: ManuscriptProvenance): string {
  return [
    '## Manuscript Provenance Report',
    '',
    `**Chapters**: ${mp.totalChapters}`,
    `**Total lines**: ${mp.totalLines}`,
    '',
    `### Aggregate`,
    `- **Author**: ${mp.authorPercent.toFixed(1)}%`,
    `- **AI-generated**: ${mp.aiPercent.toFixed(1)}%`,
    `- **AI-modified by author**: ${mp.aiModifiedPercent.toFixed(1)}%`,
    '',
    '### Per Chapter',
    '| Chapter | Author % | AI % |',
    '|---------|----------|------|',
    ...mp.perChapter.map(c => `| ${c.chapter} | ${c.authorPercent.toFixed(1)}% | ${c.aiPercent.toFixed(1)}% |`),
  ].join('\n');
}